<a href="https://colab.research.google.com/github/sayalivadya1654-cell/Data__Science/blob/main/2_Advance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with advance python #

# NUMPY
- NumPy stands for Numerical Python.
- It is the fundamental library for numerical computing in Python.
- It is mainly used to work with arrays, mathematical operations, statistics, linear algebra, and scientific computing.

## Python list vs Numpy array
- list is slower, consumes more memory and can stores hetergenous data, whereas numpy array is faster, consume less memory stores homogenous data.

 ## 1. Installing NumPy

In [ ]:
pip install Numpy

In [ ]:
# verssion
np.__version__

'2.0.2'

## 2. Importing NumPy
- import → Python keyword to load a library
- numpy → Library name
- as np → Alias (short name)
- np → Used by convention

In [ ]:
import numpy as np

## 1. Creating 1D array
- An array is a collection of elements of the same data type
- A 1D array contains data in a single row (one list).
- It has only one axis.
- Syntax:

In [ ]:
# syntax
import numpy as np
arr = np.array([10, 20, 30, 40])

In [ ]:
# creating array
# 1D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(["sayali", 22, 2026])
arr

array(['sayali', '22', '2026'], dtype='<U21')

## 2. Creating 2D Array
- A 2D array is a list of lists.
- It represents data in rows and columns, like an Excel sheet.
- Syntax:

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# 2D array :
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Creating 3d array
- Multiple 2D arrays stacked together

In [ ]:
arr = np.array([
    [               # Matrix 0
        [1, 2],     # Row 0
        [3, 4]      # Row 1
    ],

    [               # Matrix 1
        [5, 6],     # Row 0
        [7, 8]      # Row 1
    ]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# A. Attributes / Array Properties
- array properties contains
1. ndim
2. shape
3. size
4. dtype
5. itemsize
6. nbytes
7. T

## 1. Shape
- shape tells the size of each dimension.
- It returns the number of rows and columns.
- (output--> shape: (row, column))
- Syntax:


In [ ]:
# syntax
arr.shape

(2, 3)

In [ ]:
# array attributes:
print("shape:", arr2.shape)  # output--> shape: (row, column)

shape: (2, 3)


## 2. dtype (Data Type)
- dtype tells the type of data stored in the array.
- Common Data Types
1. int32 / int64	    ---> Integer numbers
2. float32 / float64	---> Decimal numbers
3. bool	              ---> True or False
4. str / Unicode      ---> (<U)	Text values
- Syntax:

In [ ]:
# syntax
arr.dtype

dtype('int64')

In [ ]:
# data types:
arr2.dtype

dtype('int64')

## 3. size
- size returns the total number of elements in the array.
- Syntax:

In [ ]:
# syntax
arr.size

6

In [ ]:
# size:
arr2.size

6

## 4. ndim (Number of Dimensions)
- ndim tells how many dimensions (axes) an array has.
- Syntax

In [ ]:
arr.ndim

2

In [ ]:
# dimentions:
arr2.ndim

2

In [ ]:
arr1.ndim

1

# Type conversion

In [ ]:
arr_float = arr1.astype(float)
# converted to float
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float64


# mathematical array operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("addition :",a + b)
print("multiplication : ",a * b)
print("division :",a / b)
print("substraction :",a - b)

addition : [11 22 33]
multiplication :  [10 40 90]
division : [10. 10. 10.]
substraction : [ 9 18 27]


# B. NumPy Array Indexing & Slicing

## 1. Indexing
- Indexing means accessing one or more specific elements from an array using their position (index).
- Every element in a NumPy array has a unique position called an index.
- Index numbering always starts from 0.
- Indexing is used to retrieve a single element or modify its value.

## Types of Indexing
1. Positive Indexing
2. Negative Indexing
3. 1D Indexing
4. 2D Indexing
5. 3D Indexing
6. Fancy Indexing
7. Boolean Indexing


| Array Type | Structure             | Syntax                     | Example        |
| ---------- | --------------------- | -------------------------- | -------------- |
| **1D**     | One row               | `arr[index]`               | `arr[3]`       |
| **2D**     | Rows + Columns        | `arr[row, column]`         | `arr[1, 2]`    |
| **3D**     | Matrix + Row + Column | `arr[matrix, row, column]` | `arr[1, 0, 1]` |


In [ ]:
# 1. positive indexing in 1D array
# Starts from left to right.
# syntax: array[index]
arrr = np.array([10,20,30,40,50])
print(arrr)
print(arrr[0])
print(arrr[2])

[10 20 30 40 50]
10
30


In [ ]:
# 2. Negative Indexing in 2D array
# Starts from right to left.
# syntax: array[index]
print(arr1[-1])
print(arr1[-3])
print(arr1[2:-3])
print(arr1[::-1])

5
3
[]
[5 4 3 2 1]


In [ ]:
# example of both
print(arr1)
print(arr1[0])
print(arr1[2:4])
print(arr1[-5:])
print(arr1[::-1])    # negative indexing only
print(arr1[1:4])

[1 2 3 4 5]
1
[3 4]
[1 2 3 4 5]
[5 4 3 2 1]
[2 3 4]


In [ ]:
# 3. 2D Array Indexing
# A 2D array contains rows and columns.
# syntax: array[row, column] or array[row][column]
ar = np.array([
    [10,20,30],
    [30,40,50],
    [50,80,10]
])
print(ar[0,0])
print(ar[1,1])
print(ar[2,2])

10
40
10


In [ ]:
# 4. 3D Array Indexing
# 3D array consists of multiple 2D arrays stacked together.
# syntax: array[matrix, row, column] or array[matrix][row][column]
arr = np.array([
    [                # -------- Matrix 0 (First 2D array) --------
        [1,2],       # Row 0 of Matrix 0
        [3,4]        # Row 1 of Matrix 0
    ],
    [                # -------- Matrix 1 (Second 2D array) --------
        [5,6],       # Row 0 of Matrix 1
        [6,7]        # Row 1 of Matrix 1
    ]
])
print(arr[0,0,0])    # Matrix = 0, Row = 0, Column = 0
print(arr[1,0,1])    # Matrix = 1, Row = 0, Column = 1

1
6


## 2. Slicing
- Slicing means selecting multiple continuous elements from an array.
- Instead of one value, Indexing →
30, Slicing → 20 30 40
- ** syntax: array[start:stop:step]**
- Parameter	Meaning
1. start → Starting index (Included ✅)
2. stop	 → Ending index (Excluded ❌)
3. step  → Skip interval


In [ ]:
# 1D slicing
arr = np.array([10,20,30,40,50,60])
print(arr)
print(arr[:])    # entire array
print(arr[:3])   # first three element
print(arr[2:])   # from index 2
print(arr[1:5])  # middle elements
print(arr[::2])  # Every Second Element
print(arr[::-1])  # reverse array

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[10 20 30]
[30 40 50 60]
[20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
# 2D slicing
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,:])  # entire first row
print(arr[1,:])  # entire second row
print(arr[2,:])  # entire third row
print(arr[0:2,:])# first two rows
print(arr[:,1:]) # last row
print(arr[1:3,1:3]) # middle block



[10 20 30]
[40 50 60]
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[50 60]
 [80 90]]


In [ ]:
# 3D slicing
arr = np.array([
[
[1,2],
[3,4]
],

[
[5,6],
[7,8]
]
])
print(arr[0,:,:]) # first matrix
print(arr[1,:,:]) # second matrix
print(arr[:,0,:]) # First Row of Every Matrix
print(arr[:,1,:]) # Second Row of Every Matrix
print(arr[:,:,0]) # First Column of Every Matrix
print(arr[:,:,1]) # Second Column of Every Matrix

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[1 3]
 [5 7]]
[[2 4]
 [6 8]]


| Feature | Indexing           | Slicing                  |
| ------- | ------------------ | ------------------------ |
| Purpose | Access one element | Access multiple elements |
| Returns | Scalar (usually)   | Array                    |
| Syntax  | `arr[2]`           | `arr[1:4]`               |
| Example | `arr[1,2]`         | `arr[:,1:]`              |


In [ ]:
import numpy as np
# from python list
arr_list = np.array([1, 2, 3, 4, 5])
print(arr_list)

[1 2 3 4 5]


In [ ]:
# from python tuple
arr_tuple = np.array((10, 20, 30))
print(arr_tuple)

[10 20 30]


In [ ]:
# basic slicing using arange()
arr = np.arange(10)
arr[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2d[0]) # 1st row
print(arr2d[1]) # 2nd row
print(arr2d[2]) # 3rd row
print(arr2d[:,1]) # middle element from each row
print(arr2d[:2])

[10 20 30]
[40 50 60]
[70 80 90]
[20 50 80]
[[10 20 30]
 [40 50 60]]


# **Practise Questions on Indexing & Slicing**

In [ ]:
# Create a 1D NumPy array and print the first element.
# also print the last element of a NumPy array using negative indexing.
# Access the third element of a 1D array.
# Print every second element of a NumPy array.
# Slice the first four elements from an array.
# Slice the last three elements of an array.
# Reverse a NumPy array using slicing.
arr = np.array([10,30,50,60,44,23])
print(arr[0])
print(arr[-1])
print(arr[2])
print(arr[::2])
print(arr[0:4])
print(arr[-4:-1])
print(arr[::-1])

10
23
50
[10 50 44]
[10 30 50 60]
[50 60 44]
[23 44 60 50 30 10]


In [ ]:
# Create a 2D array and print the element at the second row, third column.
# Print the entire first row of a 2D array.
# Print the entire second column of a 2D array.
arr = np.array([
    [11,12,13],
    [14,15,16]
])
print(arr[1,2])
print(arr[0,:])
print(arr[1,:])

16
[11 12 13]
[14 15 16]


In [ ]:
# create a 2D  numpy array using the values [[1,2,3],[4,5,6]], write a program to create array and display its shapes, size,ndim,and datatype
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [ ]:
# create a 2D  numpy array using the values [[1,2],[3,4],[5,6],[7,8]], write a program to create array and display its shapes, size,ndim
arr = np.array([
    [1,2,3],
    [3,4,5],
    [4,5,6],
    [6,7,8]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(4, 3)
12
2


# C. NumPy Array Creation Functions
-  numpy array creation uses following functions
1. **np.array()**: Creates a NumPy array from a Python list, tuple, or other sequence.
2. **np.zeros**(): Creates an array filled entirely with 0s.
3. **np.ones()**: Creates an array filled entirely with 1s.
4. **np.empty()**: Creates an array without initializing values (contains arbitrary memory values).
5. **np.full()**: Creates an array where every element is the same specified value.
6. **np.arange()**: Creates an array with evenly spaced values using a specified step size.
7. **np.linspace()**: Creates an array with a specified number of evenly spaced values between two limits.
8. **np.eye()**: Creates a 2D identity matrix with 1s on the main diagonal and 0s elsewhere.
9. **np.identity()**: Creates a square identity matrix of the given size.
10. **np.diag()**: Creates a diagonal matrix from an array or extracts the diagonal of a matrix.
11. **np.random.*()** : Generates random numbers, random arrays, or random selections using different random functions.

## 1. using np.zeros() and np.ones()
- **np.zeros()** Creates an array filled with 0, Default data type is float,Can create 1D, 2D, 3D arrays
- syntax : **np.zeros(shape, dtype=float)**
- Parameters
- shape → Number of rows and columns
- dtype → Data type (optional)

- **np.ones()** Creates an array filled with 1
- syntax: **np.ones(shape, dtype=float)**

In [ ]:
zeros_arr = np.zeros((2,3))   # np.zeros(row, column)
ones_arr = np.ones((2,3))
print(zeros_arr)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
# Create 2x4 matrix
arr = np.ones((2,4))  # default datatype float
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
# Integer ones
arr = np.ones((3,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## 2. using np.arange
- Works exactly like Python's range() but returns a NumPy array.
- syntax: **np.arange(start, stop, step)**

In [ ]:
arr_range = np.arange(0, 10, 2)  # start, stop, step
print(arr_range)

[0 2 4 6 8]


In [ ]:
arr_range = np.arange(0, 50, 4)  # start, stop, step
print(arr_range)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48]


In [ ]:
import numpy as np
# Start from 2 and stop before 10
arr = np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


## 3. using np.linespace()
- Creates evenly spaced numbers between two values.
- Unlike arange(), you specify how many values you want.
- syntax:**np.linspace(start, stop, num=50)**
- start:	Starting value
- stop:	Ending value (included)
- num:	Number of values

In [ ]:
import numpy as np
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
# Six values from 1 to 5
arr = np.linspace(1,5,6)
print(arr)

[1.  1.8 2.6 3.4 4.2 5. ]


# D. Random Module
- Used to generate random numbers.
- np.random contains
1. rand()
2. randint()
3. randn()
4. random()
5. choice()
6. seed()
7. shuffle()
8. permutation()

In [ ]:
rand_arr = np.random.rand(2,3)   # uniform (0,1)
randn_arr = np.random.randn(2,3) # normal distribution
randint_arr = np.random.randint(1,10,(2,3))  # integrs
print(rand_arr)
print(randn_arr)
print(randint_arr)

[[0.48637658 0.13182855 0.26820012]
 [0.95424982 0.04287485 0.93504025]]
[[-0.7170977   0.70984914 -0.99427322]
 [-0.62741689 -0.04101462  0.58625501]]
[[8 1 5]
 [1 1 5]]


In [ ]:
import random
arr = np.random.choice([10,20,30,40,50], size = 3) # Randomly selects values from a sequence.
print(arr)

[20 30 50]


In [ ]:
import numpy as np
np.random.seed(42) # Sets the random seed so results are reproducible.
print(np.random.randint(1,10,5))

[7 4 8 5 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
# Shuffle the original array
np.random.shuffle(arr) # shuffle arrany in place
print(arr)

[5 1 4 3 2]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
# Create a shuffled copy
new_arr = np.random.permutation(arr) # Returns a shuffled copy without changing the original.
print("Original:", arr)
print("Shuffled:", new_arr)

Original: [1 2 3 4 5]
Shuffled: [5 2 1 4 3]


# PANDAS

# 1. Installing pandas

In [ ]:
pip install pandas

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
import pandas as pd

# creating a series

In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([10,20,30,40,50])
print(s_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([100,200,300,400,500,600,700])
print(s_list)

0    100
1    200
2    300
3    400
4    500
5    600
6    700
dtype: int64


In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([22,45,78,90,56])
t_list = pd.Series([11,45,89,67,43])
u_list = pd.Series(["s1","s2","s3","s4","s5"])
print(s_list)
print(t_list)
print(u_list)

0    22
1    45
2    78
3    90
4    56
dtype: int64
0    11
1    45
2    89
3    67
4    43
dtype: int64
0    s1
1    s2
2    s3
3    s4
4    s5
dtype: object


# from a Numpy array

In [ ]:
arr = np.array([1,2,3,4,5])
s_arr = pd.Series(arr)
print(s_arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
arr = np.array(["sayali","bookes","pen"])
arr1 = np.array(["rose","sunflower","lily"])
t_arr = pd.Series(arr)
u_arr1 = pd.Series(arr1)
print(t_arr)
print(u_arr1)

0    sayali
1    bookes
2       pen
dtype: object
0         rose
1    sunflower
2         lily
dtype: object


# From a dictionary

In [ ]:
data = {"a":100,"b":200,"c":300}
s_dict = pd.Series(data)
print(s_dict)

a    100
b    200
c    300
dtype: int64


In [ ]:
data1 = {"name: ":"sayali","age: ":22,"education: ":"btech","domain: ":"data science"}
data2 = {"subject1: ":99,"subject2: ":78,"subject3: ": 87}
data3 = {"city: ":"pune","location: ":"karve nagar"}
t_dict = pd.Series(data1)
u_dict = pd.Series(data2)
v_dict = pd.Series(data3)
print(t_dict)
print(u_dict)
print(v_dict)

name:                sayali
age:                     22
education:            btech
domain:        data science
dtype: object
subject1:     99
subject2:     78
subject3:     87
dtype: int64
city:                pune
location:     karve nagar
dtype: object


# From list to dictinoary

In [ ]:
data = [{"name ":"sayali","age ": 22,"location ": "pune"},{"name ": "alice","age ": 23, "location ":"nagpur"}]
df_list_dict = pd.DataFrame(data)
print(df_list_dict)

    name   age  location 
0  sayali    22      pune
1   alice    23    nagpur


In [ ]:
data1 = [{"name":"alice","collage":"coep","passing year":2026},{"name":"john","collage":"VNIT","passing year": 2026}]
data2 = [{"flowers":"rose","books":"wings of fire"},{"flowers":"lotus","books":"harry potter"}]
d_dict = pd.DataFrame(data1)
e_dict = pd.DataFrame(data2)
print(d_dict)
print(e_dict)

    name collage  passing year
0  alice    coep          2026
1   john    VNIT          2026
  flowers          books
0    rose  wings of fire
1   lotus   harry potter


# from numpy array

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
df_array = pd.DataFrame(arr, columns = ["A","B","C"])
print(arr)
print(df_array)

[[1 2 3]
 [4 5 6]]
   A  B  C
0  1  2  3
1  4  5  6


In [ ]:
arr1 = np.array ([[100,200,300],[400,500,500],[700,400,200]])
arr2 = np.array ([["name","age"],["alice",22]])
df_array1 = pd.DataFrame(arr1,columns = ["1","2","3"])
df_array2 = pd.DataFrame(arr2,columns = ["AA","BB"])
df_array3 = pd.DataFrame(arr2,columns = ["011","022"])
print(df_array1)
print(df_array2)
print(df_array3)

     1    2    3
0  100  200  300
1  400  500  500
2  700  400  200
      AA   BB
0   name  age
1  alice   22
     011  022
0   name  age
1  alice   22


# From external files

In [ ]:
# csv
try:
  df_csv = pd.read_csv("D:/Dataset/face")
  print(df_csv.head())
except FileNotFoundError:
  print("file is not in folder please add it first")

file is not in folder please add it first


In [ ]:
# Step 1: Clone the GitHub repository
!git clone https://github.com/Pradipwasre/Data-Science-.git

# Step 2: Move into the repository
%cd /content/Data-Science-

# Step 3: Verify current working directory
!pwd

# Step 4: List all files and folders
!ls

# Step 5: Show the complete folder structure
!find .

Cloning into 'Data-Science-'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 92 (delta 37), reused 39 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (92/92), 348.31 KiB | 3.38 MiB/s, done.
Resolving deltas: 100% (37/37), done.
/content/Data-Science-
/content/Data-Science-
 1_python	     'Anaconda & NumPy.ipynb'
 2_fastAPI	      class.ipynb
 3_streamlit	      Data-Science-
 4_GenAI	      excel-data-analysis-notes.md
 5_SQL		      excel-formulas-and-functions_2.md
 6_Statistics	      oops.ipynb
 7_Machine_Learning   README.md
 9_Deep_Learning      Zomato_Sales_Excel_Formulas_Classroom.xlsx
.
./Anaconda & NumPy.ipynb
./2_fastAPI
./2_fastAPI/README.md
./excel-formulas-and-functions_2.md
./Zomato_Sales_Excel_Formulas_Classroom.xlsx
./1_python
./1_python/08_OOPs.ipynb
./1_python/09_Exception.ipynb
./1_python/13_pandas.ipynb
./1_python/04_dict.ipynb
./1_python/07_loop.ipynb
./1_p

In [ ]:
# Step 6: Import pandas
import pandas as pd

# Step 7: Read the Excel file
df = pd.read_excel("Zomato_Sales_Excel_Formulas_Classroom.xlsx")

# Step 8: Display the first 5 rows
df.head()

,Order ID,Store ID,Order Date,Cuisine,Category,Quantity,Price per Item,Discount %,Sales Amount,Delivery Time (min),Rating,Payment Mode,Store Name (Explicit Ref),Store City (Structured Ref),Rating Category (Nested IF),Order Size Tag (AND/OR),Price per Rating Pt (IFERROR)
0,ORD1001,STR05,2025-03-04 00:00:00,Italian,Veg,6,129.0,0.20,619.2,20.0,2.1,Wallet,Zomato - Hyderabad Store,Hyderabad,Poor,Bulk & Discounted,61.428571
1,ORD1002,STR02,2025-02-25 00:00:00,Italian,Veg,5,179.0,0.20,716.0,41.0,NaN,Card,Zomato - Delhi Store,Delhi,Not Rated,Bulk & Discounted,No Rating Yet
2,ORD1003,STR08,2025-05-31 00:00:00,Fast Food,Veg,2,449.0,0.15,763.3,36.0,2.5,Cash,Zomato - Ahmedabad Store,Ahmedabad,Average,Standard Order,179.6
3,ORD1004,STR06,2025-01-27 00:00:00,South Indian,Non-Veg,1,229.0,0.10,206.1,53.0,4.4,Cash,Zomato - Chennai Store,Chennai,Good,Standard Order,52.045455
4,ORD1005,STR12,2025-04-28 00:00:00,Mughlai,Veg,4,129.0,0.20,412.8,33.0,3.7,Cash,Zomato - Indore Store,Indore,Good,Bulk & Discounted,34.864865
