<a href="https://colab.research.google.com/github/sayalivadya1654-cell/Data__Science/blob/main/2_Advance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with advance python #

# NUMPY
- NumPy stands for Numerical Python.
- It is the fundamental library for numerical computing in Python.
- It is mainly used to work with arrays, mathematical operations, statistics, linear algebra, and scientific computing.

## Python list vs Numpy array
- list is slower, consumes more memory and can stores hetergenous data, whereas numpy array is faster, consume less memory stores homogenous data.

 ## 1. Installing NumPy

In [ ]:
pip install Numpy

In [ ]:
# verssion
np.__version__

'2.0.2'

## 2. Importing NumPy
- import → Python keyword to load a library
- numpy → Library name
- as np → Alias (short name)
- np → Used by convention

In [ ]:
import numpy as np

## 1. Creating 1D array
- An array is a collection of elements of the same data type
- A 1D array contains data in a single row (one list).
- It has only one axis.
- Syntax:

In [ ]:
# syntax
import numpy as np
arr = np.array([10, 20, 30, 40])

In [27]:
# creating array
# 1D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(["sayali", 22, 2026])
arr

array(['sayali', '22', '2026'], dtype='<U21')

## 2. Creating 2D Array
- A 2D array is a list of lists.
- It represents data in rows and columns, like an Excel sheet.
- Syntax:

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# 2D array :
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Creating 3d array
- Multiple 2D arrays stacked together

In [18]:
arr = np.array([
    [               # Matrix 0
        [1, 2],     # Row 0
        [3, 4]      # Row 1
    ],

    [               # Matrix 1
        [5, 6],     # Row 0
        [7, 8]      # Row 1
    ]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Attributes

## 1. Shape
- shape tells the size of each dimension.
- It returns the number of rows and columns.
- (output--> shape: (row, column))
- Syntax:


In [ ]:
# syntax
arr.shape

(2, 3)

In [ ]:
# array attributes:
print("shape:", arr2.shape)  # output--> shape: (row, column)

shape: (2, 3)


## 2. dtype (Data Type)
- dtype tells the type of data stored in the array.
- Common Data Types
1. int32 / int64	    ---> Integer numbers
2. float32 / float64	---> Decimal numbers
3. bool	              ---> True or False
4. str / Unicode      ---> (<U)	Text values
- Syntax:

In [ ]:
# syntax
arr.dtype

dtype('int64')

In [ ]:
# data types:
arr2.dtype

dtype('int64')

## 3. size
- size returns the total number of elements in the array.
- Syntax:

In [ ]:
# syntax
arr.size

6

In [ ]:
# size:
arr2.size

6

## 4. ndim (Number of Dimensions)
- ndim tells how many dimensions (axes) an array has.
- Syntax

In [ ]:
arr.ndim

2

In [ ]:
# dimentions:
arr2.ndim

2

In [28]:
arr1.ndim

1

# Type conversion

In [ ]:
arr_float = arr1.astype(float)
# converted to float
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float64


# simple array operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("addition :",a + b)
print("multiplication : ",a * b)
print("division :",a / b)
print("substraction :",a - b)

addition : [11 22 33]
multiplication :  [10 40 90]
division : [10. 10. 10.]
substraction : [ 9 18 27]


# NumPy Array Indexing & Slicing

## 1. Indexing
- Indexing means accessing one or more specific elements from an array using their position (index).
- Every element in a NumPy array has a unique position called an index.
- Index numbering always starts from 0.
- Indexing is used to retrieve a single element or modify its value.

## Types of Indexing
1. Positive Indexing
2. Negative Indexing
3. 1D Indexing
4. 2D Indexing
5. 3D Indexing
6. Fancy Indexing
7. Boolean Indexing


In [21]:
# 1. positive indexing in 1D array
# Starts from left to right.
arrr = np.array([10,20,30,40,50])
print(arrr)
print(arrr[0])
print(arrr[2])

[10 20 30 40 50]
10
30


In [40]:
# 2. Negative Indexing in 2D array
# Starts from right to left.
print(arr1[-1])
print(arr1[-3])
print(arr1[2:-3])
print(arr1[::-1])

5
3
[]
[5 4 3 2 1]


In [44]:
# example of both
print(arr1)
print(arr1[0])
print(arr1[2:4])
print(arr1[-5:])
print(arr1[::-1])    # negative indexing only
print(arr1[1:4])

[1 2 3 4 5]
1
[3 4]
[1 2 3 4 5]
[5 4 3 2 1]
[2 3 4]


In [53]:
# 3. 2D Array Indexing
# A 2D array contains rows and columns.
ar = np.array([
    [10,20,30],
    [30,40,50],
    [50,80,10]
])
print(ar[0,0])
print(ar[1,1])
print(ar[2,2])

10
40
10


In [ ]:
# 4. 3D Array Indexing
# 3D array consists of multiple 2D arrays stacked together.
