<a href="https://colab.research.google.com/github/sayalivadya1654-cell/Data__Science/blob/main/2_Advance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with advance python #

# NUMPY
- NumPy stands for Numerical Python.
- It is the fundamental library for numerical computing in Python.
- It is mainly used to work with arrays, mathematical operations, statistics, linear algebra, and scientific computing.

## Python list vs Numpy array
- list is slower, consumes more memory and can stores hetergenous data, whereas numpy array is faster, consume less memory stores homogenous data.

 ## 1. Installing NumPy

In [ ]:
pip install Numpy

In [ ]:
# verssion
np.__version__

'2.0.2'

## 2. Importing NumPy
- import → Python keyword to load a library
- numpy → Library name
- as np → Alias (short name)
- np → Used by convention

In [ ]:
import numpy as np

## 1. Creating 1D array
- An array is a collection of elements of the same data type
- A 1D array contains data in a single row (one list).
- It has only one axis.
- Syntax:

In [ ]:
# syntax
import numpy as np
arr = np.array([10, 20, 30, 40])

In [27]:
# creating array
# 1D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(["sayali", 22, 2026])
arr

array(['sayali', '22', '2026'], dtype='<U21')

## 2. Creating 2D Array
- A 2D array is a list of lists.
- It represents data in rows and columns, like an Excel sheet.
- Syntax:

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# 2D array :
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Creating 3d array
- Multiple 2D arrays stacked together

In [18]:
arr = np.array([
    [               # Matrix 0
        [1, 2],     # Row 0
        [3, 4]      # Row 1
    ],

    [               # Matrix 1
        [5, 6],     # Row 0
        [7, 8]      # Row 1
    ]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Attributes

## 1. Shape
- shape tells the size of each dimension.
- It returns the number of rows and columns.
- (output--> shape: (row, column))
- Syntax:


In [ ]:
# syntax
arr.shape

(2, 3)

In [ ]:
# array attributes:
print("shape:", arr2.shape)  # output--> shape: (row, column)

shape: (2, 3)


## 2. dtype (Data Type)
- dtype tells the type of data stored in the array.
- Common Data Types
1. int32 / int64	    ---> Integer numbers
2. float32 / float64	---> Decimal numbers
3. bool	              ---> True or False
4. str / Unicode      ---> (<U)	Text values
- Syntax:

In [ ]:
# syntax
arr.dtype

dtype('int64')

In [ ]:
# data types:
arr2.dtype

dtype('int64')

## 3. size
- size returns the total number of elements in the array.
- Syntax:

In [ ]:
# syntax
arr.size

6

In [ ]:
# size:
arr2.size

6

## 4. ndim (Number of Dimensions)
- ndim tells how many dimensions (axes) an array has.
- Syntax

In [ ]:
arr.ndim

2

In [ ]:
# dimentions:
arr2.ndim

2

In [28]:
arr1.ndim

1

# Type conversion

In [ ]:
arr_float = arr1.astype(float)
# converted to float
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float64


# mathematical array operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("addition :",a + b)
print("multiplication : ",a * b)
print("division :",a / b)
print("substraction :",a - b)

addition : [11 22 33]
multiplication :  [10 40 90]
division : [10. 10. 10.]
substraction : [ 9 18 27]


# NumPy Array Indexing & Slicing

## 1. Indexing
- Indexing means accessing one or more specific elements from an array using their position (index).
- Every element in a NumPy array has a unique position called an index.
- Index numbering always starts from 0.
- Indexing is used to retrieve a single element or modify its value.

## Types of Indexing
1. Positive Indexing
2. Negative Indexing
3. 1D Indexing
4. 2D Indexing
5. 3D Indexing
6. Fancy Indexing
7. Boolean Indexing


| Array Type | Structure             | Syntax                     | Example        |
| ---------- | --------------------- | -------------------------- | -------------- |
| **1D**     | One row               | `arr[index]`               | `arr[3]`       |
| **2D**     | Rows + Columns        | `arr[row, column]`         | `arr[1, 2]`    |
| **3D**     | Matrix + Row + Column | `arr[matrix, row, column]` | `arr[1, 0, 1]` |


In [21]:
# 1. positive indexing in 1D array
# Starts from left to right.
# syntax: array[index]
arrr = np.array([10,20,30,40,50])
print(arrr)
print(arrr[0])
print(arrr[2])

[10 20 30 40 50]
10
30


In [40]:
# 2. Negative Indexing in 2D array
# Starts from right to left.
# syntax: array[index]
print(arr1[-1])
print(arr1[-3])
print(arr1[2:-3])
print(arr1[::-1])

5
3
[]
[5 4 3 2 1]


In [44]:
# example of both
print(arr1)
print(arr1[0])
print(arr1[2:4])
print(arr1[-5:])
print(arr1[::-1])    # negative indexing only
print(arr1[1:4])

[1 2 3 4 5]
1
[3 4]
[1 2 3 4 5]
[5 4 3 2 1]
[2 3 4]


In [53]:
# 3. 2D Array Indexing
# A 2D array contains rows and columns.
# syntax: array[row, column] or array[row][column]
ar = np.array([
    [10,20,30],
    [30,40,50],
    [50,80,10]
])
print(ar[0,0])
print(ar[1,1])
print(ar[2,2])

10
40
10


In [61]:
# 4. 3D Array Indexing
# 3D array consists of multiple 2D arrays stacked together.
# syntax: array[matrix, row, column] or array[matrix][row][column]
arr = np.array([
    [                # -------- Matrix 0 (First 2D array) --------
        [1,2],       # Row 0 of Matrix 0
        [3,4]        # Row 1 of Matrix 0
    ],
    [                # -------- Matrix 1 (Second 2D array) --------
        [5,6],       # Row 0 of Matrix 1
        [6,7]        # Row 1 of Matrix 1
    ]
])
print(arr[0,0,0])    # Matrix = 0, Row = 0, Column = 0
print(arr[1,0,1])    # Matrix = 1, Row = 0, Column = 1

1
6


## 2. Slicing
- Slicing means selecting multiple continuous elements from an array.
- Instead of one value, Indexing →
30, Slicing → 20 30 40
- ** syntax: array[start:stop:step]**
- Parameter	Meaning
1. start → Starting index (Included ✅)
2. stop	 → Ending index (Excluded ❌)
3. step  → Skip interval


In [69]:
# 1D slicing
arr = np.array([10,20,30,40,50,60])
print(arr)
print(arr[:])    # entire array
print(arr[:3])   # first three element
print(arr[2:])   # from index 2
print(arr[1:5])  # middle elements
print(arr[::2])  # Every Second Element
print(arr[::-1])  # reverse array

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[10 20 30]
[30 40 50 60]
[20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [77]:
# 2D slicing
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,:])  # entire first row
print(arr[1,:])  # entire second row
print(arr[2,:])  # entire third row
print(arr[0:2,:])# first two rows
print(arr[:,1:]) # last row
print(arr[1:3,1:3]) # middle block



[10 20 30]
[40 50 60]
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[50 60]
 [80 90]]


In [83]:
# 3D slicing
arr = np.array([
[
[1,2],
[3,4]
],

[
[5,6],
[7,8]
]
])
print(arr[0,:,:]) # first matrix
print(arr[1,:,:]) # second matrix
print(arr[:,0,:]) # First Row of Every Matrix
print(arr[:,1,:]) # Second Row of Every Matrix
print(arr[:,:,0]) # First Column of Every Matrix
print(arr[:,:,1]) # Second Column of Every Matrix

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[1 3]
 [5 7]]
[[2 4]
 [6 8]]


| Feature | Indexing           | Slicing                  |
| ------- | ------------------ | ------------------------ |
| Purpose | Access one element | Access multiple elements |
| Returns | Scalar (usually)   | Array                    |
| Syntax  | `arr[2]`           | `arr[1:4]`               |
| Example | `arr[1,2]`         | `arr[:,1:]`              |


In [104]:
import numpy as np
# from python list
arr_list = np.array([1, 2, 3, 4, 5])
print(arr_list)

[1 2 3 4 5]


In [106]:
# from python tuple
arr_tuple = np.array((10, 20, 30))
print(arr_tuple)

[10 20 30]


In [133]:
# basic slicing
arr = np.arange(10)
arr[2:7]

array([2, 3, 4, 5, 6])

# **Practise Questions on Indexing & Slicing**

In [93]:
# Create a 1D NumPy array and print the first element.
# also print the last element of a NumPy array using negative indexing.
# Access the third element of a 1D array.
# Print every second element of a NumPy array.
# Slice the first four elements from an array.
# Slice the last three elements of an array.
# Reverse a NumPy array using slicing.
arr = np.array([10,30,50,60,44,23])
print(arr[0])
print(arr[-1])
print(arr[2])
print(arr[::2])
print(arr[0:4])
print(arr[-4:-1])
print(arr[::-1])

10
23
50
[10 50 44]
[10 30 50 60]
[50 60 44]
[23 44 60 50 30 10]


In [102]:
# Create a 2D array and print the element at the second row, third column.
# Print the entire first row of a 2D array.
# Print the entire second column of a 2D array.
arr = np.array([
    [11,12,13],
    [14,15,16]
])
print(arr[1,2])
print(arr[0,:])
print(arr[1,:])

16
[11 12 13]
[14 15 16]


# usinf np.zeros() and np.ones()

In [110]:
zeros_arr = np.zeros((2,3))   # np.zeros(row, column)
ones_arr = np.ones((2,3))
print(zeros_arr)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


## using np.range

In [116]:
arr_range = np.arange(0, 10, 2)  # start, stop, step
print(arr_range)

[0 2 4 6 8]


In [119]:
arr_range = np.arange(0, 50, 4)  # start, stop, step
print(arr_range)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48]


## using np.linespace()

In [125]:
import numpy as np
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


# using np.random()

In [130]:
rand_arr = np.random.rand(2,3)   # uniform (0,1)
randn_arr = np.random.randn(2,3) # normal distribution
randint_arr = np.random.randint(1,10,(2,3))  # integrs
print(rand_arr)
print(randn_arr)
print(randint_arr)

[[0.76415704 0.99515486 0.17580788]
 [0.05760552 0.37553638 0.67418286]]
[[ 0.338889   -0.53046274 -1.18470829]
 [-1.0368842   1.67045731  1.92283315]]
[[2 4 8]
 [8 4 3]]
